[app]
# 和 Gin 的 Mode对应: debug release test
mode = "debug"
port = 9003
jwt_secret = "aaxxbbcceee"
jwt_expired_hour = 2

[mysql]
host = "localhost"
username = "root"
password = "123456"
port = 3306
dbname = "aifuxi_cool"

[log]
filename = "./logs/dev.log"
max_size = 10
max_backups = 10
max_age = 30
